sudo: required
dist: trusty

language: c

compiler:
 - gcc

before_install:
 - sudo apt-get update
 - sudo apt-get install -y libbsd-dev libev-dev
 - uname -a
install:
 - make --debug
 - ./build/unix.bin &
