sudo: required
dist: trusty

language: c

compiler:
 - gcc

install:
 - sudo apt-get update
 - sudo apt-get install -y libbsd-dev libev-dev
 - uname -a
script:
 - make -j2
 - sudo make install
deploy:
 - ./tests/all.sh
